[package]
name = "slp-search"
authors = ["Nick Condron <ncondron42@gmail.com>"]
description = "Filter slp replays or search for events"
repository = "https://github.com/ncondron42/slp-search"
version = "0.2.0"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peppi = "1.0.0-alpha.6"
clap = { version = "3.1.17", features = ["derive"] }
